<?
$aMenuLinks = Array(
	Array(
		"facebook", 
		"https://www.facebook.com/pages/francesco-marconi/1443857612576101", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"vk", 
		"http://vk.com/fmarconi_ru", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"youtube", 
		"http://www.youtube.com/channel/UCV5buNVv6_uVn225pkX3DFw/videos", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"twitter", 
		"https://twitter.com/fmarconi_ru", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"instagram", 
		"https://instagram.com/fmarconi.ru", 
		Array(), 
		Array(), 
		"" 
	)
);
?>